name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: files
      uses: Ana06/get-changed-files@v2.1.0
      with:
        format: 'json'

    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/_test/Gemfile
      with:
        ruby-version: 3.1.1
        bundler-cache: true
    - name: Run jekyll
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/_test/Gemfile
      run: JEKYLL_ENV=development bundle exec jekyll build
    - name: Run html-proofer
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/_test/Gemfile
      run: bundle exec ruby _test/html-proofer/run.rb
    - name: Generate md files
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/_test/Gemfile
      run: |
        echo '${{ steps.files.outputs.added_modified }}'>_test/result/changed-files.json
        bundle exec ruby _test/generate-report/analyze.rb
    - uses: actions/upload-artifact@v3
      with:
        name: report
        path: _test/result

