name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache bundle gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-${{ env.cache-name }}-
          ${{ runner.os }}-gem-
          ${{ runner.os }}-
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1
        bundler-cache: true
    - name: Install Bundler
      run: gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
    - name: Bundle install
      run: bundle install --path=vendor/bundle --jobs 4 --retry 3
    - name: Run jekyll
      run: JEKYLL_ENV=development bundle exec jekyll build
    - name: Run html-proofer
      run: bundle exec ruby code/html-proofer/main.rb || true
    - uses: actions/upload-artifact@v3
      with:
        name: report
        path: _report
  
